config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'inquiries/edit'
  get 'inquiries/index'
  get 'inquiries/new'
  get 'item/pay'
  get 'item/sale'
  get 'line_items/purchasehistory'


  resources :inquiries
  resources :line_items
  resources :carts
  resources :products
  get 'registrations/registration'
  devise_for :users, controllers:{
   registrations: 'registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/item_controller.rb
require './EC/Sale'
class ItemController < ApplicationController
  def sale
  end

  def pay
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    Payjp::Charge.create(
      :amount => @cart.total_price,
      :card => params['payjp-token'],
      :currency => 'jpy'
    )

    intbox = Sale.foo(1,100)
 
    if intbox.floor <= 1
     @probability = 1 # 判定変数 ・・・ 真1
    else 
     @probability = 0 # 判定変数 ・・・ 偽0
    end 
 
    @i = Magnification.fa
 
    @a = 1.0 - @i
 
    @a.round(1) #支払い分
 
    @i.round(1) #割合い
  
  end
end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/item/pay.html.erb
<% if @probability == 1 %>
   <h1>あなたは当選しました!!</h1>
   <h1>おめでとうございます!!</h1>
   <div style="width: 20vw" >
     <%= image_tag("ticket.png") %><h2 style="position: relative; bottom: 6vw; left: 22vw; font-size: 5vw;">: x1</h2>
     <h2>割引券ゲット</h2>
   </div>
<% elsif @probability == 0 %>
      <h1>今回はハズレです。残念...</h1>
<% end %>
<%= link_to '支払い確定', item_sale_path %>

app/views/item/sale.html.erb
<h1>支払いが終わりました！！</h1>
<%= link_to "購入履歴書", line_items_purchasehistory_path(format: "pdf") , style:"margin-right: 2vw;"%>
<%= link_to 'TOPへ', @cart, method: :delete %>