config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'inquiries/edit'
  get 'inquiries/index'
  get 'inquiries/new'
  get 'item/pay'
  get 'item/sale'
  get 'line_items/purchasehistory'


  resources :inquiries
  resources :line_items
  resources :carts
  resources :products
  get 'registrations/registration'
  devise_for :users, controllers:{
   registrations: 'registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
def index
    @members = Form.order("name")
end

def show
end

def new
    @article = Form.new
end

def edit
    @article = Form.find(params[:id])
end

def create
    @article = Form.new(form_params)
    if @article.save
        redirect_to :action => "index" , notice: "登録完了"
    else
        render "new"
    end
end

def update
    @article = Form.find(params[:id])
    @article.assign_attributes(form_params)
    if @article.save
        redirect_to :action => "index" , notice: "変更完了"
    else
        render "edit"
    end

end

def destroy
    @article = Form.find(params[:id])
    @article.destroy
    redirect_to :action => "index" ,notice:"削除完了"
end

private 

def form_params
params.require(:form).permit(
    :name,
    :phone,
    :adress,
    :form
)
end

end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/_form.html.erb
<%= render "shared/errors", obj: @article %>

<table>
<tr>
  <th><%= form.label :お名前 %></th>
  <td><%= form.text_field :name %></td>
</tr>

<tr>
  <th><%= form.label :電話番号 %></th>
  <td><%= form.text_field :phone %></td>
</tr>

<tr>
  <th><%= form.label :メールアドレス %></th>
  <td><%= form.text_field :adress %></td>
</tr>

<tr>
  <th><%= form.label :お問い合わせ内容 %></th>
  <td><%= form.text_field :form %></td>
</tr>





</table>

app/views/inquiries/edit.html.erb
<%= form_for @article, :url => { :controllor => :inquiries, :action => :update} do |form| %>
    <%= render "form", form: form %>
        <div><%= form.submit %></div>
<% end %>

app/views/inquiries/index.html.erb
<div class="toolbar">
<%= link_to "新規作成", :new_inquiry , style:"font-size: 1.5vw;"%>
</div>

<% if @members.present? %>
  <table class="list">
    <thead>
      <tr>
        <th>お名前</th>
        <th>電話番号</th>
        <th>メールアドレス</th>
        <th>お問い合わせ内容</th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= member.name %></td>
          <td><%= member.phone %></td>
          <td><%= member.adress %></td>
          <td><%= member.form %></td>
          <td><%= link_to"編集",edit_inquiry_path(member) , style:"font-size: 1.5vw;"%></td>
          <td><%= link_to"削除", inquiry_path(member), method: :delete,
          data: { confirm: "削除してもよろしいですか?"} , style:"font-size: 1.5vw;"%></td>
        </tr>
        <% end %>
        <% else %>
        <p>情報なし</p>
        <% end %>
     <%= link_to "Home", products_path , style:"font-size: 1.5vw;"%>
  </tbody>
</table>

app/views/inquiries/new.html.erb
<%= form_for @article, :url => { :controllor => :inquiries, :action => :create} do |form| %>
    <%= render "form", form: form %>
        <div><%= form.submit %></div>
<% end %>